# Site settings
title: Tired
header-img: "img/autumn2.jpg"
tagline: "吉光片羽"  
description: "在遙遠的地方 一切虔誠終必相遇"  
baseurl: ""
url: "http://www.shuaiqiang.top"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "Tired"
  email: 13391516523@163.com
  bio: "明朝即長路 惜取此時心"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: Tired
twitter_username: Tired_Lapland  
github_username: Tired  
facebook_username: Tired_Lapland  
weibo_username: Tired  
zhihu_username: Tired  

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Tired/Beijing

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Tired"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : Tired
  disqus :
      short_name : Tired

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation